name: Node CI

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
      - name: npm install
        run: make install
      - name: Run linter
        run:
          make lint